### PR TITLE
Updated data as of Dec 2015

### PR DESCRIPTION
**Pull request by gabehammersmith**

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @gabehammersmith!

//cc @konklone, looks like sanders may now be HSTS preload!

**Comment by konklone** [comment]
Hmm, I don't see it on the [preload list](https://chromium.googlesource.com/chromium/src/+/master/net/http/transport_security_state_static.json) or the [pending review list](https://hstspreload.appspot.com/pending).

The root of the site does have a `preload` flag but it lacks an `includeSubDomains` flag:

```
$ curl --head https://berniesanders.com
HTTP/1.1 302 Moved Temporarily
...
Strict-Transport-Security: max-age=15552000; preload
```

They could manually request the Chrome team add the entry without subdomains, but they'd be much better served just fixing their subdomains and then relying on automatic inclusion.

**Comment by gabehammersmith** [comment]
Cheers @benbalter!

@konklone There are some logistical challenges involved with getting TLS up on some of the berniesanders.com subdomains. We hope to be able to add `includeSubDomains` in early 2016!

**Comment by konklone** [comment]
@gabehammersmith That's great to hear, and I'm greatly looking forward to it! =)

**Pull request merged**
